using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Scripting.Hosting;

namespace MagyarTV
{
    public class Channel
    {
        public string Name { get; set; }
        public string ID { get; set; }
        public string URI { get; set; }
        public string IndexFeed { get; set; }
        public bool IsRecording { get; set; }
        public bool IsPlaying { get; set; }
        public VideoMetadata StreamInfo { get; set; }
        public string GetChannelURI(string feed)
        {
            var currentAssembly = Assembly.GetEntryAssembly();
            var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
            string cmd = Path.Combine(currentDirectory, "Python", "getURI.py");

            try
            {
                ProcessStartInfo start = new ProcessStartInfo();
                start.FileName = String.Format("{0}\\Python27\\Python.exe", currentDirectory);
                start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, "-i " + feed);
                start.UseShellExecute = false;// Do not use OS shell
                start.CreateNoWindow = true; // We don't need new window
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
                using (Process process = Process.Start(start))
                {
                    using (StreamReader reader = process.StandardOutput)
                    {
                        string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                        string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                        return result;
                    }
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

    }

}
